### ISSUE TITLE
not able to install tensorflow federated in windows 10 

### ISSUE THREAD

**Issue by somiljain7** [tensorflow/federated#788] opened 2019-12-03 11:18 UTC
![Screenshot (4)](https://user-images.githubusercontent.com/42209500/70046778-ba487f80-15ec-11ea-8e57-61a56c6a023a.png)

**Comment by jkr26** [comment] 2019-12-04 03:03
Duplicate of #779; please see that issue for Windows questions, or register your desire there.

Thanks for your interest in TFF!

**Closed by jkr26** 2019-12-04 03:03 UTC

**Comment by SlienceClaire** [comment] 2020-05-04 12:34
@somiljain7 I meet the same question that  "Could not find a version that satisfies the requirement tensorflow-addons==0.6.0 (from versions: 0.7.0, 0.7.1, 0.8.1, 0.8.2, 0.8.3, 0.9.0, 0.9.1)
ERROR: No matching distribution found for tensorflow-addons==0.6.0". Can I ask about how can you solve it ?

**Comment by AshiakerWang** [comment] 2020-05-14 02:35
> Duplicate of #779; please see that issue for Windows questions, or register your desire there.
> 
> Thanks for your interest in TFF!

Is there any plan to add windows support recently?
