### ISSUE TITLE
How to train on multiple GPUs?

### ISSUE THREAD

**Issue by vonsterov** [tensorflow/federated#333] opened 2019-04-12 02:39 UTC
Hello,
The model is created with keras, following code is tried to train on 2 gpus:

> from tensorflow.keras.utils import multi_gpu_model
> model = multi_gpu_model(model, gpus=2)

but get an error:

> Traceback (most recent call last):
>   File "/aiml/code/fl_CNN_train_v0.5.py", line 336, in <module>
>     iterative_process = tff.learning.build_federated_averaging_process(model_fn) 
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow_federated/python/learning/federated_averaging.py", line 149, in build_federated_averaging_process
>     model_fn, client_fed_avg, server_optimizer_fn)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow_federated/python/learning/framework/optimizer_utils.py", line 286, in build_model_delta_optimizer_process
>     dummy_model_for_metadata = model_utils.enhance(model_fn())
>   File "/aiml/code/fl_CNN_train_v0.5.py", line 325, in model_fn
>     return tff.learning.from_compiled_keras_model(keras_model, sample_batch)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow_federated/python/learning/model_utils.py", line 193, in from_compiled_keras_model
>     return enhance(_TrainableKerasModel(keras_model, dummy_batch))
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow_federated/python/learning/model_utils.py", line 437, in __init__
>     inner_model.test_on_batch(**dummy_batch)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py", line 1253, in test_on_batch
>     outputs = self.test_function(inputs)  # pylint: disable=not-callable
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/backend.py", line 3073, in __call__
>     self._make_callable(feed_arrays, feed_symbols, symbol_vals, session)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/backend.py", line 3019, in _make_callable
>     callable_fn = session._make_callable_from_options(callable_opts)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1471, in _make_callable_from_options
>     return BaseSession._Callable(self, callable_options)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1425, in __init__
>     session._session, options_ptr, status)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Tensor conv2d_input:0, specified in either feed_devices or fetch_devices was not found in the Graph
> Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f53902a8898>>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1455, in __del__
>     self._session._session, self._handle, status)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.InvalidArgumentError: No such callable handle: 444335424

How to train on multiple GPUs using TFF?

**Comment by wangyixu14** [comment] 2019-05-17 12:56
Could I know if you have succeed in using on single GPU to train the TFF project? It seems that TFF doesn't support GPU training right now?

**Comment by vonsterov** [comment] 2019-05-20 09:11
> Could I know if you have succeed in using on single GPU to train the TFF project? It seems that TFF doesn't support GPU training right now?

@wangyixu14  I can train TFF model with one single GPU with TFF 0.2.0. However, the GPU utilization is not high, it will be idle periodically. 
I also tried it with 0.4.0 but failed.

**Comment by michaelreneer** [comment] 2019-05-31 15:32
Currently the GPU architecture is failing to build. @krzys-ostrowski might be able to provide more insight.

**Comment by michaelreneer** [comment] 2019-05-31 15:38
Duplicate of #361

**Closed by michaelreneer** 2019-05-31 15:38 UTC
