### ISSUE TITLE
Reusing/Importing techniques in research folder 

### ISSUE THREAD

**Issue by anupamme** [tensorflow/federated#887] opened 2020-08-02 23:12 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

I would like to import one of the techniques in a research folder in another one e.g. research/robust_aggregation in targeted_attack/

But when I write 

from tensorflow_federated.python.research.robust_aggregation import robust_federated_aggregation as rfa

in research/targeted_attack/attacked_fedavg.py, I get the error

ModuleNotFoundError: No module named 'tensorflow_federated.python.research.robust_aggregation'

Similarly, if I try to use one of the modules within targeted_attack in robust_aggregation, I get the same error.

So inter-operability of these techniques seems like an issue. Can you guide me how I can get around this error.

**Describe the solution you'd like**

I would like to be able to use any technique in a subfolder of research in another subfolder. Currently they are just standalone techniques.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

I have not considered any alternative yet. But if you can guide me I will be happy to look at alternatives.

**Additional context**
Add any other context about the feature request here.

**Comment by jkr26** [comment] 2020-08-03 17:06
Hi @anupamme 

There has been some discussion on the sharing of research code in TFF--usually, "core TFF" thinks of each research project as an individual extension, and prefers not to take on the maintenance burden that promotion to a directly-importable package would imply.

I think for now the TFF preferred method for taking a dependency on TFF research code is to [build from source](https://github.com/tensorflow/federated/blob/master/docs/install.md#build-the-tensorflow-federated-python-package-from-source).

However, [this discussion](https://github.com/tensorflow/federated/issues/841) remains ongoing--for this reason, assigning @michaelreneer here.

**Comment by michaelreneer** [comment] 2020-08-03 20:19
Duplicate of #841

**Closed by michaelreneer** 2020-08-03 20:19 UTC
Labels: enhancement
