### ISSUE TITLE
AttributeError: module 'tensorflow._api.v1.data.experimental' has no attribute 'NestedStructure'

### ISSUE THREAD

**Issue by afaf-taik** [tensorflow/federated#611] opened 2019-06-25 16:24 UTC
Hello, 
I was able to run my code just 2 days ago on colab, but now I can't because of this error AttributeError: module 'tensorflow._api.v1.data.experimental' has no attribute 'NestedStructure' . The error is related to tff.learning.build_federated_averaging_process(model_fn). 
 What is the source of this problem ? 
Thank you

**Comment by jkr26** [comment] 2019-06-25 16:52
Duplicate of #609 

Thanks!
Keith

**Closed by jkr26** 2019-06-25 16:52 UTC
