### ISSUE TITLE
WARNING:tensorflow:5 out of the last 9 calls to <function Model.make_test_function.<locals>.test_function at 0x7fc94ec49f28> triggered tf.function retracing. 

### ISSUE THREAD

**Issue by aynesss** [tensorflow/federated#2794] opened 2022-05-09 09:37 UTC
Why I find this warning after 3d round
`
WARNING:tensorflow:5 out of the last 9 calls to <function Model.make_test_function.<locals>.test_function at 0x7fc94ec49f28> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
`

**Comment by michaelreneer** [comment] 2022-08-19 21:54
Closing this issue because there is not enough information to answer it. If this is still an issue, please provide more information including the minimal steps to reproduce the issue and information about your system.

**Closed by michaelreneer** 2022-08-19 21:54 UTC
