### ISSUE TITLE
Tutorial and Notebook: Errors

### ISSUE THREAD

**Issue by vicMio** [tensorflow/federated#1469] opened 2021-06-15 13:43 UTC
While running the building_your_own_federated_learning_algorithm.ipynb notebook, I have the following errors
ERROR: tensorflow 2.5.0 has requirement grpcio~=1.34.0, but you'll have grpcio 1.37.1 which is incompatible.
ERROR: tensorflow 2.5.0 has requirement keras-nightly~=2.5.0.dev, but you'll have keras-nightly 2.6.0.dev2021061500 which is incompatible.
ERROR: spacy 2.2.4 has requirement tqdm<5.0.0,>=4.38.0, but you'll have tqdm 4.28.1 which is incompatible.
ERROR: pymc3 3.11.2 has requirement cachetools>=4.2.1, but you'll have cachetools 3.1.1 which is incompatible.
ERROR: fbprophet 0.7.1 has requirement tqdm>=4.36.1, but you'll have tqdm 4.28.1 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.

**Comment by vicMio** [comment] 2021-06-15 14:11
I just ran the building_your_own_federated_learning_algorithm.ipynb that is in your docs (federated/docs/tutorials/building_your_own_federated_learning_algorithm.ipynb) with the following commands in the beginning to fix other problems:

!pip install tensorflow==2.1
!pip install --quiet --upgrade tensorflow-federated==0.13.1

**Comment by XinyiYS** [comment] 2022-04-27 03:54
I can confirm the error reported by @vicMio. As I tried to run the same colab notebook in GoogleColab (federated/docs/tutorials/building_your_own_federated_learning_algorithm.ipynb).

The installation gives errors:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spacy 2.2.4 requires tqdm<5.0.0,>=4.38.0, but you have tqdm 4.28.1 which is incompatible.
pymc3 3.11.4 requires cachetools>=4.2.1, but you have cachetools 3.1.1 which is incompatible.
panel 0.12.1 requires tqdm>=4.48.0, but you have tqdm 4.28.1 which is incompatible.
fbprophet 0.7.1 requires tqdm>=4.36.1, but you have tqdm 4.28.1 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
```
Subsequently, `import tensorflow_federated as tff` also gives an error
```
TypeError                                 Traceback (most recent call last)
[<ipython-input-5-8d5e013f6c62>](https://localhost:8080/#) in <module>()
      1 import tensorflow as tf
----> 2 import tensorflow_federated as tff

7 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow_federated/python/common_libs/structure.py](https://localhost:8080/#) in <module>()
    263 
    264 def to_odict(struct: Struct,
--> 265              recursive: bool = False) -> collections.OrderedDict[str, Any]:
    266   """Returns `struct` as an `OrderedDict`, if possible.
    267 

TypeError: 'type' object is not subscriptable
```


Can I ask if there is an update on this? Or if there is a work-around?

**Comment by SamuelGong** [comment] 2022-05-20 07:13
> I can confirm the error reported by @vicMio. As I tried to run the same colab notebook in GoogleColab (federated/docs/tutorials/building_your_own_federated_learning_algorithm.ipynb).
> 
> The installation gives errors:
> 
> ```
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> spacy 2.2.4 requires tqdm<5.0.0,>=4.38.0, but you have tqdm 4.28.1 which is incompatible.
> pymc3 3.11.4 requires cachetools>=4.2.1, but you have cachetools 3.1.1 which is incompatible.
> panel 0.12.1 requires tqdm>=4.48.0, but you have tqdm 4.28.1 which is incompatible.
> fbprophet 0.7.1 requires tqdm>=4.36.1, but you have tqdm 4.28.1 which is incompatible.
> datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
> albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
> ```
> 
> Subsequently, `import tensorflow_federated as tff` also gives an error
> 
> ```
> TypeError                                 Traceback (most recent call last)
> [<ipython-input-5-8d5e013f6c62>](https://localhost:8080/#) in <module>()
>       1 import tensorflow as tf
> ----> 2 import tensorflow_federated as tff
> 
> 7 frames
> [/usr/local/lib/python3.7/dist-packages/tensorflow_federated/python/common_libs/structure.py](https://localhost:8080/#) in <module>()
>     263 
>     264 def to_odict(struct: Struct,
> --> 265              recursive: bool = False) -> collections.OrderedDict[str, Any]:
>     266   """Returns `struct` as an `OrderedDict`, if possible.
>     267 
> 
> TypeError: 'type' object is not subscriptable
> ```
> 
> Can I ask if there is an update on this? Or if there is a work-around?

I encountered the same issue, and fixed it by first uninstall tensorflow-federated and then installing tensorflow-federated-nightly by `pip install tensorflow-federated-nightly`.

**Comment by is-laoyang** [comment] 2022-08-18 06:26
I am getting error in import tensorflow_federated as tff: NameError: name 'python' is not defined

> NameError                                 Traceback (most recent call last)
[<ipython-input-26-a23308ec3f7c>](https://localhost:8080/#) in <module>
      3 import numpy as np
      4 import tensorflow as tf
----> 5 import tensorflow_federated as tff
      6 
      7 np.random.seed(0)

[/usr/local/lib/python3.7/dist-packages/tensorflow_federated/__init__.py](https://localhost:8080/#) in <module>
     79 # the directory structure. The python import statements above implicitly add
     80 # these to locals().
---> 81 del python  # pylint:disable=undefined-variable
     82 del proto  # pylint:disable=undefined-variable

NameError: name 'python' is not defined

**Comment by michaelreneer** [comment] 2022-08-18 16:43
@XinyiYS 

> The installation gives errors:
> 
> ```
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> spacy 2.2.4 requires tqdm<5.0.0,>=4.38.0, but you have tqdm 4.28.1 which is incompatible.
> pymc3 3.11.4 requires cachetools>=4.2.1, but you have cachetools 3.1.1 which is incompatible.
> panel 0.12.1 requires tqdm>=4.48.0, but you have tqdm 4.28.1 which is incompatible.
> fbprophet 0.7.1 requires tqdm>=4.36.1, but you have tqdm 4.28.1 which is incompatible.
> datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
> albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
> ```

Google colab has a lot of dependencies that are not compatible with TFF, you can try and remove these with `!pip uninstall --yes <foo>` or ignore the errors. 

> `TypeError: 'type' object is not subscriptable`

Google colab is currently on Python 3.8, which will cause this error.

@is-laoyang

Are you getting this error when using the tutorial in Google colab, or are you getting this error locally?

**Comment by michaelreneer** [comment] 2022-08-18 16:45
I'm going to close this issue because it's expected that we get these kinds of error when running the tutorials in Google colab because Google colab comes with a lot of existing packages that TFF is not compatible with.

Note you can ignore these errors or you can remove the unneeded packages before installing `tensorflow-federated`.

**Closed by michaelreneer** 2022-08-18 16:45 UTC
Labels: bug
