### ISSUE TITLE
install and import problem

### ISSUE THREAD

**Issue by drkingman** [tensorflow/federated#235] opened 2019-03-12 03:34 UTC
I have followed the install steps
`virtualenv --python python3 "venv"
source ./venv/bin/activate
pip install --upgrade pip
(veno) pip install --upgrade tensorflow_federated
`
and I have installed `bazel 0.23.2`
when testing `python -c "import tensorflow_federated as tff; tff.federated_computation(lambda: 'Hello, World!')()"` it returned `bash: !': event not found`

when testing the demo, it shows error `import tensorflow_federated as tff`
![图片](https://user-images.githubusercontent.com/22471616/54172868-8a83a580-44ba-11e9-839c-1f9759bd1038.png)

**Comment by hu6360567** [comment] 2019-03-12 06:19
You may check the version of tensorflow.
Tensorflow does not have a contrib module for 2.0 version.
#224

**Comment by michaelreneer** [comment] 2019-03-12 16:07
Thanks @hu6360567, this is correct. Duplicate of #224.

**Comment by drkingman** [comment] 2019-03-14 07:59
> Duplicate of #224

actually since I updated to 0.2.0 version,  it still returned `bash: !': event not found`

**Comment by michaelreneer** [comment] 2019-03-14 15:55
Sorry I should have been more clear previously. The error that I initially noticed actually had nothing to do with `bash: !': event not found` and instead was the line in your screenshot reading `AttributeError: module 'tensorflow' has not attribute 'contrib'`. This error was described in #224.

I suspect that you tried to re-run these commands using your old virtual environment? I am not sure if `pip install --upgrade tensorflow_federated` will downgrade the version of TF. I would recommend running `pip freeze` and replying with the output from that command. I suspect that you would find tensorflow `2.0.0a` in that list. If this is the case, the fix is to simply delete your virtual environment and create a new one.

**Closed** 2019-03-22 15:31 UTC
