### ISSUE TITLE
Variable initialization failure with Keras + FeatureColumns

### ISSUE THREAD

**Issue by jpgard** [tensorflow/federated#783] opened 2019-11-08 21:47 UTC
I'm trying to train a Keras model which uses `FeatureColumn`s, and in particular, embedding columns. This requires that the embedding columns be "inside" the Keras model instead of e.g. constructing a dense tensor in a preprocessing step prior to model training.

However, TFF seems to fail for *any* FeatureColumns which require initializing lookup variables (not just the embedding columns -- categorical encoding columns cause this issue as well).

Any suggestions on alternative workflows which can still produce trainable embeddings for categorical inputs, or is it possible to address the underlying issue for TFF?

Code to reproduce is in a colab notebook [here](https://colab.research.google.com/drive/1Z8szSsj7oWQLBK4D08m6ioGnfL8_DRZ_)

The model can build, and can successfully execute `keras_model.train_on_batch()` and `keras_model.test_on_batch()`in a non-federated process, but when a federated averaging process is build from the model, it fails with the stack trace below.

```
---------------------------------------------------------------------------
FailedPreconditionError                   Traceback (most recent call last)
<ipython-input-25-6841cae1566c> in <module>()
      1 iterative_process = tff.learning.build_federated_averaging_process(
----> 2         model_fn)
      3 print(iterative_process.initialize.type_signature)
      4 state = iterative_process.initialize()

6 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in __call__(self, *args, **kwargs)
   1472         ret = tf_session.TF_SessionRunCallable(self._session._session,
   1473                                                self._handle, args,
-> 1474                                                run_metadata_ptr)
   1475         if run_metadata:
   1476           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

FailedPreconditionError: Table not initialized.
	 [[{{node sequential/dense_features/sex_indicator_1/hash_table_Lookup/LookupTableFindV2}}]]
```

**Comment by ZacharyGarrett** [comment] 2019-11-13 17:11
This looks like an issue inside TFF.

Unfortunately TFF is currently only extracting variables here:

https://github.com/tensorflow/federated/blob/547eeae6b65f6951504dfb49615a782306a6e097/tensorflow_federated/python/learning/keras_utils.py#L370-L379

and then adding them to an initialization op here:
https://github.com/tensorflow/federated/blob/547eeae6b65f6951504dfb49615a782306a6e097/tensorflow_federated/python/core/impl/tensorflow_serialization.py#L292-L313

TFF later executes the initializers in the ReferenceExecutor here:
https://github.com/tensorflow/federated/blob/547eeae6b65f6951504dfb49615a782306a6e097/tensorflow_federated/python/core/impl/reference_executor.py#L341-L342

and the EagerExecutor here:
https://github.com/tensorflow/federated/blob/547eeae6b65f6951504dfb49615a782306a6e097/tensorflow_federated/python/core/impl/eager_executor.py#L90-L93

But it looks like the lookup table has its own initializer op that needs to run. Seems like we need to find a way to get the initializer for the lookup table and add it to the `init_op` and we'll be golden.

**Comment by jpgard** [comment] 2019-11-13 23:57
I am assuming from this answer that there isn't a workaround -- is that correct? Any general idea of what the timeline for a fix might be?

**Comment by ZacharyGarrett** [comment] 2019-11-14 22:54
**Note**: I believe the issue is from TFF not running the required initializers for `tf.feature_column.categorical_column_with_vocabulary_list` (and likely any `tf.feature_column.categorical_column_with_*`). Usage of `tf.feature_column.embedding_column` I expect to be fine.

Correct, an easy workaround is not readily apparent. If it's feasible, possibly encoding the string features to integer IDs on disk before reading into TensorFlow, but this is quite unfortunate.

I'm not sure how easy it is to get a handle on the initializer for the lookup table; which would help estimate how long it will take to fix. This may be fixed by moving the computation serialization to TF 2.0-style SavedModel, but that is a ways away.

**Comment by jpgard** [comment] 2019-11-18 17:07
I will look into this again, but I believe this issue was also encountered with the embedding columns alone. 

If this issue is not affecting embedding columns, it seems that  there may be a workaround: split the model input so that the embedding layer(s) are inside the Keras models, but the categorical features are outside the Keras models (e.g. in a preprocessing step), since these don't need to be trained. In that case, everything would work.

I will try this out soon.

**Comment by jpgard** [comment] 2019-12-01 01:50
Following up; I was able to try this without the categorical columns (e.g. only numeric and embedding columns). In that case, there is still an error in the call to `build_federated_averaging_process()`, but the traceback is different. Full traceback below:

```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-6841cae1566c> in <module>()
      1 iterative_process = tff.learning.build_federated_averaging_process(
----> 2         model_fn)
      3 print(iterative_process.initialize.type_signature)
      4 state = iterative_process.initialize()

11 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/impl/api.py in wrapper(*args, **kwargs)
    261       except Exception as e:  # pylint:disable=broad-except
    262         if hasattr(e, 'ag_error_metadata'):
--> 263           raise e.ag_error_metadata.to_exception(e)
    264         else:
    265           raise

AttributeError: in converted code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/feature_column/dense_features.py:135 call
        self._state_manager)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/feature_column/feature_column_v2.py:3192 get_dense_tensor
        return self._get_dense_tensor_internal(sparse_tensors, state_manager)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/feature_column/feature_column_v2.py:3145 _get_dense_tensor_internal
        embedding_weights)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/feature_column/feature_column_v2.py:3138 _get_dense_tensor_internal_helper
        max_norm=self.max_norm)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/embedding_ops.py:798 safe_embedding_lookup_sparse
        max_norm=max_norm)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/embedding_ops.py:488 embedding_lookup_sparse
        params, ids, partition_strategy=partition_strategy, max_norm=max_norm)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/embedding_ops.py:323 embedding_lookup
        transform_fn=None)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/embedding_ops.py:135 _embedding_lookup_and_transform
        with ops.colocate_with(params[0]):
    /usr/lib/python3.6/contextlib.py:81 __enter__
        return next(self.gen)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:4104 _colocate_with_for_gradient
        with self.colocate_with(op, ignore_existing):
    /usr/lib/python3.6/contextlib.py:81 __enter__
        return next(self.gen)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:4153 colocate_with
        op = _op_to_colocate_with(op, self)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:6555 _op_to_colocate_with
        return v.handle.op
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1094 op
        "Tensor.op is meaningless when eager execution is enabled.")

    AttributeError: Tensor.op is meaningless when eager execution is enabled.
```
I also experimented with disabling eager execution via `tf.compat.v1.disable_eager_execution()`; in that case, there is still an error, but the traceback is:

```

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-24-6841cae1566c> in <module>()
      1 iterative_process = tff.learning.build_federated_averaging_process(
----> 2         model_fn)
      3 print(iterative_process.initialize.type_signature)
      4 state = iterative_process.initialize()

11 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/impl/api.py in wrapper(*args, **kwargs)
    261       except Exception as e:  # pylint:disable=broad-except
    262         if hasattr(e, 'ag_error_metadata'):
--> 263           raise e.ag_error_metadata.to_exception(e)
    264         else:
    265           raise

ValueError: in converted code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/feature_column/dense_features.py:135 call
        self._state_manager)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/feature_column/feature_column_v2.py:3192 get_dense_tensor
        return self._get_dense_tensor_internal(sparse_tensors, state_manager)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/feature_column/feature_column_v2.py:3145 _get_dense_tensor_internal
        embedding_weights)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/feature_column/feature_column_v2.py:3138 _get_dense_tensor_internal_helper
        max_norm=self.max_norm)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/embedding_ops.py:761 safe_embedding_lookup_sparse
        [sparse_ids, sparse_weights]) as scope:
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:6239 __enter__
        g_from_inputs = _get_graph_from_inputs(self._values)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:5876 _get_graph_from_inputs
        _assert_same_graph(original_graph_element, graph_element)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:5811 _assert_same_graph
        (item, original_item))

    ValueError: SparseTensor(indices=Tensor("sequential/dense_features_1/occupation_embedding/to_sparse_input/indices:0", shape=(None, 2), dtype=int64), values=Tensor("sequential/dense_features_1/occupation_embedding/hash_table_Lookup/LookupTableFindV2:0", shape=(None,), dtype=int64), dense_shape=Tensor("sequential/dense_features_1/occupation_embedding/to_sparse_input/dense_shape:0", shape=(2,), dtype=int64)) must be from the same graph as Tensor("dense_features_1/occupation_embedding/embedding_weights/Read/ReadVariableOp:0", shape=(14, 4), dtype=float32).
```

Code to replicate is [here](https://colab.research.google.com/drive/1rCATWcXPOAo5DxlOHlaM0WLGLiVDXVse#scrollTo=MIJx8b8N723C); just switch on/off the boolean parameters `embedding_columns`and `categorical_columns` in the call to `make_feature_layer()` to view the different failure modes.

**Comment by jkr26** [comment] 2020-02-25 21:43
Hi @jpgard 

We actually just noticed that our test for this issue which was failing is now passing; [this commit](https://github.com/tensorflow/federated/commit/22895c49f9cd7889d80de22d018b10e0c84ece9b) enables this test again.

We are wondering--are you still seeing this issue?

**Closed** 2020-04-03 16:50 UTC
Labels: contributions welcome
