### ISSUE TITLE
proximal_strength strange behavior

### ISSUE THREAD

**Issue by liyakun** [tensorflow/federated#3473] opened 2023-01-06 13:10 UTC
**Describe the bug**
When I set the value of `proximal_strength` for FedProx training, I got the following error 

```Python
    The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yli/financial-fl/scripts/credit_default_fedprox.py", line 298, in <module>
    msg, local_setting, setting_idx = future.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
ValueError: proximal_strength must be a nonnegative float, found 0
srun: error: serv-3328: task 0: Exited with exit code 1
```
, which seems conflict with the function documentation at https://github.com/tensorflow/federated/blob/ee2e15e95e78e28f02d4a717d04f49f724bcd71c/tensorflow_federated/python/learning/algorithms/fed_prox.py#L127, which tells the behavior when user set the value to 0.

Btw, I also tried with 0.0, which also results in error.

**Environment**
* Opensuse Tumbleweed
* Packages
    * TensorFlow Federated 0.40.0
    * TensorFlow 2.10.1
* Python 3.9

**Expected behavior**
More clear documentation which aligns with actual behavior of the function.

**Comment by zcharles8** [comment] 2023-01-09 22:55
Hi @liyakun. The error message when you input an integer proximal strength is working as intended.

I tried to repro your error with `proximal_strength=0.0` but I was not able to get a reproduction. If possible, can you post the code snippet with `0.0` that gave you an error?

**Comment by liyakun** [comment] 2023-01-12 12:43
@zcharles8 thanks for your information and sorry for the delay in my replying. 

I got the following error 

```bash
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/yli/financial-fl/scripts/credit_default_fedprox.py", line 150, in fl_training
    fed_avg = tff.learning.algorithms.build_weighted_fed_prox(
  File "/home/yli/financial-fl/.venv/lib/python3.9/site-packages/tensorflow_federated/python/learning/algorithms/fed_prox.py", line 225, in build_weighted_fed_prox
    client_work = proximal_client_work.build_model_delta_client_work(
  File "/home/yli/financial-fl/.venv/lib/python3.9/site-packages/tensorflow_federated/python/learning/templates/proximal_client_work.py", line 380, in build_model_delta_client_work
    raise ValueError(f'Provided delta_l2_regularizer must be positive,'
ValueError: Provided delta_l2_regularizer must be positive,but found: 0.0
```
with the following code snippet

```python
fed_prox = tff.learning.algorithms.build_weighted_fed_prox(
  fl_dnn.model_fn,
  proximal_strength=cfg_local.PROXIMAL_STRENGTH,
  client_optimizer_fn=lambda: tf.keras.optimizers.SGD(learning_rate=cfg_local.CLIENT_LR),
  server_optimizer_fn=lambda: tf.keras.optimizers.SGD(learning_rate=cfg_local.SERVER_LR)
)

state = fed_prox.initialize()

for round_num in range(cfg_local.NUM_ROUNDS):
    round_num = tf.constant(round_num, tf.int64)
  
    eval_metrics = fl_dnn.keras_evaluate(fed_prox.get_model_weights(state), round_num, X_test_local, y_test_local)
    result = fed_prox.next(state, federated_train_data)
    state = result.state
```

where `fl_dnn` is an instance of another separately defined class, which I think should not be related to the error. Let me know if you need more information.

**Comment by zcharles8** [comment] 2023-01-12 17:56
What was the value in `proximal_strength` that gave you that error? The error check should just be failing if it is an integer or negative.

**Comment by liyakun** [comment] 2023-01-12 20:17
@zcharles8 I gave value `0.0` for this parameter.

**Comment by zcharles8** [comment] 2023-01-13 17:43
@liyakun When I try this I get a different error message than you posted, which has to do with regularization in the client work. I see now that there's a slight discrepancy between two of the pieces; the FedProx algorithm says that the regularization can be nonnegative, but the client work component says it must be positive. I'll take a look to see which of these makes more sense and send a fix.

**Comment by zcharles8** [comment] 2023-01-13 17:45
Note that as a temporary workaround: `build_weighted_fed_avg` and `build_weighted_fed_prox` are the same algorithm when the `proximal_strength = 0.0`.

**Comment by liyakun** [comment] 2023-01-13 21:46
@zcharles8 thanks, I tried with a very small number with `build_weighted_fed_prox` just to see the effect. 

btw, I still suggest to change the value `0` in the documentation https://github.com/tensorflow/federated/blob/ee2e15e95e78e28f02d4a717d04f49f724bcd71c/tensorflow_federated/python/learning/algorithms/fed_prox.py#L127 to `0.0` as `0` is not really supported in the function to be set.

**Comment by zcharles8** [comment] 2023-01-18 16:59
@liyakun I fixed this last week but forgot to update this bug. d9b72b1c783269f006312a27057b934708ff335d corrects the behavior so that a proximal term of `0` should work. Once there's a new release (which should be sometime this week) this should be fixed for you.

**Comment by zcharles8** [comment] 2023-01-19 17:50
The most recent TFF release includes the fix, so marking as this resolved.

**Closed by zcharles8** 2023-01-19 17:50 UTC
Labels: bug
