### ISSUE TITLE
TypeError: Cannot capture a result of an unsupported type tensorflow.python.keras.engine.functional.Functional.

### ISSUE THREAD

**Issue by aynesss** [tensorflow/federated#2313] opened 2022-01-03 08:11 UTC
I would like to load a pretrained network in the inside of `create_keras_model()`
So I write this :
```
def create_keras_model():
  
    baseModel = tf.keras.models.load_model(model_path, compile=False)
 
    headModel = baseModel.output
    model_output = tf.keras.layers.Dense(3, activation="softmax", name="output")(headModel)

    model = tf.keras.Model(inputs=baseModel.input, outputs=model_output)
    
    return model

def model_fn():
    keras_model = create_keras_model()  
    return tff.learning.from_keras_model(keras_model, input_spec = input_spec, loss=tf.keras.losses.CategoricalCrossentropy(), metrics=[tf.keras.metrics.CategoricalAccuracy()])


@tff.tf_computation
def get_weights_from_disk():
   keras_model = create_keras_model()

   return keras_model

@tff.federated_computation
def server_init():

  return tff.federated_eval(get_weights_from_disk(), tff.SERVER)


old_iterproc = tff.learning.build_federated_averaging_process(model_fn=model_fn, server_optimizer_fn=lambda: tf.keras.optimizers.SGD(learning_rate=1.0), client_optimizer_fn=lambda: tf.keras.optimizers.SGD(learning_rate=0.001))
new_iterproc = tff.templates.IterativeProcess(intialize_fn=server_init,
  next_fn=old_iterproc.next)
state = new_iterproc.initialize()`

**Comment by zcharles8** [comment] 2022-01-07 16:49
Hi @aynesss. This looks like a duplicate of https://stackoverflow.com/questions/70563080/typeerror-cannot-capture-a-result-of-an-unsupported-type-tensorflow-python-kera, which has a good answer on it. Please refer to that for the solution.

**Closed by zcharles8** 2022-01-07 16:49 UTC
