### ISSUE TITLE
OSError: Proto type 'tensorflow.GraphDef' not found

### ISSUE THREAD

**Issue by devharsh** [tensorflow/federated#3523] opened 2023-01-18 17:56 UTC
```
[libprotobuf INFO google/protobuf/util/message_differencer.cc:1444] Proto type 'tensorflow.GraphDef' not found
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Input In [33], in <cell line: 9>()
      5 import tensorflow_federated as tff
      7 np.random.seed(0)
----> 9 tff.federated_computation(lambda: 'Hello, World!')()

File /usr/local/lib/python3.10/site-packages/tensorflow_federated/python/core/impl/computation/computation_impl.py:135, in ConcreteComputation.__call__(self, *args, **kwargs)
    133 def __call__(self, *args, **kwargs):
    134   arg = function_utils.pack_args(self._type_signature.parameter, args, kwargs)
--> 135   return self._context_stack.current.invoke(self, arg)

File /usr/local/lib/python3.10/site-packages/tensorflow_federated/python/core/impl/execution_contexts/sync_execution_context.py:62, in SyncExecutionContext.invoke(self, comp, arg)
     61 def invoke(self, comp, arg):
---> 62   return self._async_runner.run_coro_and_return_result(
     63       self._async_context.invoke(comp, arg))

File /usr/local/lib/python3.10/site-packages/tensorflow_federated/python/common_libs/async_utils.py:223, in AsyncThreadRunner.run_coro_and_return_result(self, coro)
    221 """Runs coroutine in the managed event loop, returning the result."""
    222 future = asyncio.run_coroutine_threadsafe(coro, self._event_loop)
--> 223 return future.result()

File /usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py:458, in Future.result(self, timeout)
    456     raise CancelledError()
    457 elif self._state == FINISHED:
--> 458     return self.__get_result()
    459 else:
    460     raise TimeoutError()

File /usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py:403, in Future.__get_result(self)
    401 if self._exception:
    402     try:
--> 403         raise self._exception
    404     finally:
    405         # Break a reference cycle with the exception in self._exception
    406         self = None

File /usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py:232, in Task.__step(***failed resolving arguments***)
    228 try:
    229     if exc is None:
    230         # We use the `send` method directly, because coroutines
    231         # don't have `__iter__` and `__next__` methods.
--> 232         result = coro.send(None)
    233     else:
    234         result = coro.throw(exc)

File /usr/local/lib/python3.10/site-packages/tensorflow_federated/python/common_libs/retrying.py:109, in retry.<locals>.retry_coro_fn(*args, **kwargs)
    107 except Exception as e:  # pylint: disable=broad-except
    108   if not retry_on_exception_filter(e):
--> 109     raise e
    110   retry_wait_ms = min(wait_max_ms, retry_wait_ms * wait_multiplier)
    111   # asyncio.sleep takes arguments in seconds.

File /usr/local/lib/python3.10/site-packages/tensorflow_federated/python/common_libs/retrying.py:99, in retry.<locals>.retry_coro_fn(*args, **kwargs)
     97 while True:
     98   try:
---> 99     result = await fn(*args, **kwargs)
    100     if retry_on_result_filter(result):
    101       retry_wait_ms = min(wait_max_ms, retry_wait_ms * wait_multiplier)

File /usr/local/lib/python3.10/site-packages/tensorflow_federated/python/core/impl/execution_contexts/async_execution_context.py:221, in AsyncExecutionContext.invoke(self, comp, arg)
    218 else:
    219   cardinalities = {}
--> 221 with self._reset_factory_on_error(self._executor_factory,
    222                                   cardinalities) as executor:
    223   py_typecheck.check_type(executor, executor_base.Executor)
    225   if arg is not None:

File /usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py:135, in _GeneratorContextManager.__enter__(self)
    133 del self.args, self.kwds, self.func
    134 try:
--> 135     return next(self.gen)
    136 except StopIteration:
    137     raise RuntimeError("generator didn't yield") from None

File /usr/local/lib/python3.10/site-packages/tensorflow_federated/python/core/impl/execution_contexts/async_execution_context.py:185, in AsyncExecutionContext._reset_factory_on_error(self, ex_factory, cardinalities)
    181 @contextlib.contextmanager
    182 def _reset_factory_on_error(self, ex_factory, cardinalities):
    183   try:
    184     # We pass a copy down to prevent the caller from mutating.
--> 185     yield ex_factory.create_executor({**cardinalities})
    186   except Exception:
    187     ex_factory.clean_up_executor({**cardinalities})

File /usr/local/lib/python3.10/site-packages/tensorflow_federated/python/core/impl/executor_stacks/python_executor_stacks.py:108, in ResourceManagingExecutorFactory.create_executor(self, cardinalities)
    106 if ex is not None:
    107   return ex
--> 108 ex = self._executor_stack_fn(cardinalities)
    109 py_typecheck.check_type(ex, executor_base.Executor)
    110 self._executors[key] = ex

File /usr/local/lib/python3.10/site-packages/tensorflow_federated/python/core/backends/native/execution_contexts.py:527, in _create_local_cpp_executor_factory.<locals>.stack_fn(cardinalities)
    525 if cardinalities.get(placements.CLIENTS) is None:
    526   cardinalities[placements.CLIENTS] = default_num_clients
--> 527 stub = service_manager.get_stub()
    528 ex = remote_executor.RemoteExecutor(stub, stream_structs=stream_structs)
    529 ex.set_cardinalities(cardinalities)

File /usr/local/lib/python3.10/site-packages/tensorflow_federated/python/core/backends/native/execution_contexts.py:511, in _create_local_cpp_executor_factory.<locals>.ServiceManager.get_stub(self)
    509   self._process.wait()
    510 # Start a process and block til the associated stub is ready.
--> 511 process, port = start_process()
    512 target = f'localhost:{port}'
    513 channel = grpc.insecure_channel(target, _GRPC_CHANNEL_OPTIONS)

File /usr/local/lib/python3.10/site-packages/tensorflow_federated/python/core/backends/native/execution_contexts.py:476, in _create_local_cpp_executor_factory.<locals>.start_process()
    470 args = [
    471     binary_path,
    472     f'--port={port}',
    473     f'--max_concurrent_computation_calls={max_concurrent_computation_calls}',
    474 ]
    475 logging.debug('Starting TFF C++ server on port: %s', port)
--> 476 return subprocess.Popen(args, stdout=sys.stdout, stderr=sys.stderr), port

File /usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py:971, in Popen.__init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask, pipesize)
    967         if self.text_mode:
    968             self.stderr = io.TextIOWrapper(self.stderr,
    969                     encoding=encoding, errors=errors)
--> 971     self._execute_child(args, executable, preexec_fn, close_fds,
    972                         pass_fds, cwd, env,
    973                         startupinfo, creationflags, shell,
    974                         p2cread, p2cwrite,
    975                         c2pread, c2pwrite,
    976                         errread, errwrite,
    977                         restore_signals,
    978                         gid, gids, uid, umask,
    979                         start_new_session)
    980 except:
    981     # Cleanup if the child failed starting.
    982     for f in filter(None, (self.stdin, self.stdout, self.stderr)):

File /usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py:1847, in Popen._execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, gid, gids, uid, umask, start_new_session)
   1845     if errno_num != 0:
   1846         err_msg = os.strerror(errno_num)
-> 1847     raise child_exception_type(errno_num, err_msg, err_filename)
   1848 raise child_exception_type(err_msg)

OSError: [Errno 8] Exec format error: '/usr/local/lib/python3.10/site-packages/tensorflow_federated/python/core/backends/native/../../../../data/worker_binary'

```

* OS Platform and Distribution: macOS Ventura 13.1
* Python package versions (e.g., TensorFlow Federated, TensorFlow):
```
pip install protobuf tensorflow tensorflow-federated
Requirement already satisfied: protobuf in /usr/local/lib/python3.10/site-packages (3.19.6)
Requirement already satisfied: tensorflow in /usr/local/lib/python3.10/site-packages (2.11.0)
Requirement already satisfied: tensorflow-federated in /usr/local/lib/python3.10/site-packages (0.45.0)
```
* Python version: Python 3.10.9

**Comment by michaelreneer** [comment] 2023-02-07 19:44
Duplicate of #3591

**Closed by michaelreneer** 2023-02-07 19:44 UTC
Labels: bug

**Comment by michaelreneer** [comment] 2023-02-07 19:45
Duplicate of #3608

**Comment by devharsh** [comment] 2023-02-07 19:48
I would like to work on this issue to support macOS with your help! :)
