### ISSUE TITLE
WARNING: Requirement '/tmp/tensorflow_federated/*.whl' looks like a filename, but the file does not exist ERROR: *.whl is not a valid wheel filename.

### ISSUE THREAD

**Issue by SheldonHH** [tensorflow/federated#1750] opened 2021-08-26 11:43 UTC
WARNING: Requirement '/tmp/tensorflow_federated/*.whl' looks like a filename, but the file does not exist
ERROR: *.whl is not a valid wheel filename.

**Comment by zcharles8** [comment] 2021-09-07 16:20
@SheldonHH Can you post more detail about the context in which you encountered this? In particular, what code you ran, and the full stack trace would be appreciated. We have an issues template you can use that would be particularly helpful.

**Comment by michaelreneer** [comment] 2022-08-19 22:05
Closing this issue because there is not enough information to reproduce the issue.

**Closed by michaelreneer** 2022-08-19 22:05 UTC
Labels: bug
