### ISSUE TITLE
Cannot import library tensorflow_federated

### ISSUE THREAD

**Issue by nikarageorgos** [tensorflow/federated#2770] opened 2022-05-02 09:01 UTC
I run Tensorflow's notebook tutorial for Federated Learning for Image Classification (https://www.tensorflow.org/federated/tutorials/federated_learning_for_image_classification) and it fails to import the library tensorflow_federated in the third code cell of the notebook despite the fact that the library is properly installed on the first cell.

 It returns error:

TypeError                                 Traceback (most recent call last)
[<ipython-input-2-a23308ec3f7c>](https://localhost:8080/#) in <module>()
      3 import numpy as np
      4 import tensorflow as tf
----> 5 import tensorflow_federated as tff
      6 
      7 np.random.seed(0)

I dont understand why this is happening. I was able to run successfully this notebook until last week.

**Comment by ElnathanTiokou** [comment] 2022-05-02 14:56
It's 2 days now I'm facing the same issue, I read elsewhere and they said we should update the python version. But still it is not working.

**Comment by ZacharyGarrett** [comment] 2022-05-02 15:34
If using https://colab.research.google.com/, installing the `0.20.0` version of TFF following the instructions at https://github.com/tensorflow/federated/issues/2748#issuecomment-1107437271 is recommended.

Otherwise including the following details would help:

- What is the output of `print(sys.version)` when run in a cell of the notebook?
- What is the output of `pip freeze`?
- Please copy-paste the entire stacktrace included with the error.

**Comment by ElnathanTiokou** [comment] 2022-05-02 15:53
Here is the type error I have while trying to import 
import tensorflow_federated as tff

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-32-dff7d3b60363>](https://localhost:8080/#) in <module>()
      1 import tensorflow as tf
----> 2 import tensorflow_federated as tff

7 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow_federated/python/common_libs/structure.py](https://localhost:8080/#) in <module>()
    263 
    264 def to_odict(struct: Struct,
--> 265              recursive: bool = False) -> collections.OrderedDict[str, Any]:
    266   """Returns `struct` as an `OrderedDict`, if possible.
    267 

TypeError: 'type' object is not subscriptable

**Comment by ElnathanTiokou** [comment] 2022-05-03 04:56
I finally got the solution: 
Try this out: 

!pip install --quiet  tensorflow-federated==0.20.0   # The latest version of tensorflow-federated is not working with the colab python version
!pip install --quiet --upgrade nest-asyncio

**Comment by ZacharyGarrett** [comment] 2022-05-03 14:55
Duplicate of #2748

**Closed by ZacharyGarrett** 2022-05-03 14:55 UTC
Labels: bug

**Comment by divya034** [comment] 2022-07-20 22:55
> If using Colab, this likely occurs because Colab is running Python 3.7 but TFF requires Python 3.9.
> 
> The following can version the local Python version.
> 
> ```python
> import sys
> print(sys.version)
> ```
> 
> If using Colab, for now follow the instructions in [#2748 (comment)](https://github.com/tensorflow/federated/issues/2748#issuecomment-1107437271)

Hi, can I please know how to configure VS code to be able to run import TensorFlow statements? Because I want to create a library for a codebase that automatically divides federated datasets to be divided among clients
