### ISSUE TITLE
Does tff.tf_computation support tf.numpy_function?

### ISSUE THREAD

**Issue by FancyXun** [tensorflow/federated#803] opened 2020-03-09 11:43 UTC
When I use tf.numpy_function in optimizer_utils.py(tensorflow_federated/python/learning/framework/optimizer_utils.py) like this

```
tensor_string_type = tff.TensorType(tf.string)
@tff.tf_computation(tensor_string_type)
    def cast_tensor_to_int(k):
        def _numpy_func(x):
            x = int(x) + 1
            return np.array(x, dtype='U100000')

        @tf.function(input_signature=[tf.TensorSpec(shape=(), dtype=tf.string)])
        def tf_function(input):
            y = tf.numpy_function(_numpy_func, [input], tf.string)
            y1 = tf.reshape(y, ())
            return y1
        return tf_function(k)
```

and I call this function in run_one_round_tff, It gives me the errors in client side

> ValueError: callback pyfunc_0 is not found
> 	 [[{{node import/StatefulPartitionedCall/PyFunc}}]] [Op:__inference_wrapped_function_13]
> Function call stack:

I don't know why this happened?

**Comment by jkr26** [comment] 2020-04-12 22:49
Hi @FancyXun 

I have been unable to reproduce this problem in our current setup (that is, with TFF 0.13.1). See the colab [here](https://colab.research.google.com/drive/15wfY6xv4LZa1oBf-mNjJXJfir1XIwLWy) for a working version of the above.

With a new version of TFF, is this fixed on your end?

**Comment by FancyXun** [comment] 2020-04-21 08:13
> Hi @FancyXun
> 
> I have been unable to reproduce this problem in our current setup (that is, with TFF 0.13.1). See the colab [here](https://colab.research.google.com/drive/15wfY6xv4LZa1oBf-mNjJXJfir1XIwLWy) for a working version of the above.
> 
> With a new version of TFF, is this fixed on your end?

Thanks!
Does this code in colab run in client side? Follow https://www.tensorflow.org/api_docs/python/tf/numpy_function , tf.numpy_function can not support  serialize

**Comment by jkr26** [comment] 2020-07-08 04:22
TFF uses its own TensorFlow serialization mechanisms, and in fact the computations the TFF runtime invokes are essentially precisely backed by the same artifact that would run them on device (a TFF [computation.proto](https://github.com/tensorflow/federated/blob/master/tensorflow_federated/proto/v0/computation.proto). If the code runs in the TFF runtime, it will run identically on device.

There are *likely* some things `numpy_function` could do that TFF's serialization mechanisms would fail to capture, but you would see this right away--the code would fail in the runtime. Likely any numpy arrays are baked into the graph as constants, for example.

**Closed by jkr26** 2020-07-08 04:22 UTC
