### ISSUE TITLE
Composition of Privacy Mechanisms in Tensorflow Federated

### ISSUE THREAD

**Issue by AHabes** [tensorflow/federated#1575] opened 2021-07-08 16:20 UTC
I have read several papers about implementing privacy in federated learning. 

It seems that the implementation in```tensorflow privacy``` is mainly based on the paper **Renyi Differential Privacy of the Sampled Gaussian Mechanism** to perform the privacy analysis and compute the orders of the RDP. 

However, it is not fully clear which composition theorem is followed to compose the Private Gaussian mechanisms at each federated round. Thanks for pointing out the paper and the theorem used for handling composition

**Comment by galenmandrew** [comment] 2021-07-13 17:16
"_compute_log_a_int" and "_compute_log_a_frac" use the formulas derived in the section "Numerically Stable Computation" of the paper you mentioned.

"_compute_eps" uses Proposition 12 from https://arxiv.org/abs/2004.00010.

"compute_rdp_sample_without_replacement" uses Theorem 27 of https://arxiv.org/pdf/1808.00087.pdf

**Comment by zcharles8** [comment] 2021-07-14 18:33
@AHabes I am closing this issue as it seems to have been answered. Feel free to re-open this if you believe the issue is not resolved.

**Closed by zcharles8** 2021-07-14 18:33 UTC
