### ISSUE TITLE
tff.federated_computation(lambda: 'Hello World!')() stuck/hanging 

### ISSUE THREAD

**Issue by Temitopeadekunle0906** [tensorflow/federated#4585] opened 2024-03-28 02:37 UTC
Help me urgently

I follow this documentation "https://www.tensorflow.org/federated/install"

!python -c "import tensorflow_federated as tff; print(tff.federated_computation(lambda: 'Hello World')())" the line of code keep running for over 6hrs now on google colab 

On Python 3.10.12

**Comment by zcharles8** [comment] 2024-03-28 16:07
HI @Temitopeadekunle0906. Can you provide the details of your environment from the bug template? In particular:

**Environment (please complete the following information):**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
* Python package versions (e.g., TensorFlow Federated, TensorFlow):
* Python version:
* Bazel version (if building from source):
* CUDA/cuDNN version:
* What TensorFlow Federated execution stack are you using?

Note: You can collect the Python package information by running `pip3 freeze`
from the command line and most of the other information can be collected using
TensorFlows environment capture
[script](https://github.com/tensorflow/tensorflow/blob/master/tools/tf_env_collect.sh).

**Comment by zcharles8** [comment] 2024-03-28 16:28
Oh, are you using colab by any chance? I just tried out some tutorials there and noticed the indefinite hang.

**Comment by zcharles8** [comment] 2024-03-28 16:29
I ask because this might be a duplicate of #4588 if you are.

**Comment by zcharles8** [comment] 2024-03-28 16:33
Okay, I'm marking this as a duplicate of #4588, and will use that issue to communicate about this. I can repro this issue, will start to investigate.

**Closed by zcharles8** 2024-03-28 16:33 UTC
Labels: bug

**Comment by Temitopeadekunle0906** [comment] 2024-03-28 16:37
Thanks Charles. Anticipating a prompt resolution
